fix: 🐛 pin pandas to 1.2 version
fixes `TypeError: _translate() missing 2 required positional arguments:
‘sparse_index’ and ‘sparse_cols’`
https://discuss.streamlit.io/t/getiing-an-error-after-deployment-of-streamlit-c/14674